services:
  ac-database:
    volumes:
      - ${DOCKER_VOL_DB:-ac-database}:/var/lib/mysql
  ac-db-import:
    volumes:
      - ${DOCKER_VOL_SQL_CUSTOM:-./data/sql/custom}:/azerothcore/data/sql/custom
    env_file:
      - "./config/custom/env.dbimport"
  ac-worldserver:
    volumes:
      - ./azerothcore-wotlk/modules:/azerothcore/modules:ro
    env_file:
      - "./config/custom/env.worldserver"
  ac-authserver:
    env_file:
      - "./config/custom/env.authserver"